baseurl      = "/"
title        = "Tea with ichigo 🍵"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "everything is a learnable skill"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Huong Do's coding journal"
  keywords = "itsmeichigo, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Tea with ichigo 🍵"
    subtitle = "Huong Do's coding journal"
    keywords = "swift, learning, tech"
    copyright = 'Huong Do'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about"

  [[menu.main]]
    identifier = "blog"
    name       = "posts"
    url        = "/posts"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/itsmeichigo"
    weight = 40

  [[params.social]]
    name = "github"
    url = "https://github.com/itsmeichigo"
    weight = 40

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/huongdt29/"
    weight = 40
